---
  # YUM
  # Can't use yum module as --setopt=obsoletes=0 is not supported
  - name: install docker-ce yum package
    command: yum install -y --setopt=obsoletes=0 docker-ce-{{ docker_ce_yum_version }}
    register: docker_installation_rpm
    until: docker_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  # DEB
  - name: install docker-ce deb package
    apt:
      name: docker-ce={{ docker_ce_apt_version }}
      state: present
      default_release: xenial
    register: docker_installation_deb
    until: docker_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"